name: PluginManager
main: org.airmc.pm.core.CorePlugin
version: 1.0
commands:
   pload:
      description: Load a specific plugin.
      usage: /pload [plugin]
   punload:
      description: Unload a specific plugin.
      usage: /punload [plugin]
   preload:
      description: Reload a specific plugin.
      usage: /preload [plugin]
